// <auto-generated />
using System;
using AzerothAPI.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzerothAPI.Data.Migrations
{
    [DbContext(typeof(BlogDb))]
    partial class BlogDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("latin1_swedish_ci")
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "latin1");

            modelBuilder.Entity("AzerothAPI.Data.Models.Blog.Displayname", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.Property<string>("DisplayName1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DisplayName");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("displayname", (string)null);
                });

            modelBuilder.Entity("AzerothAPI.Data.Models.Blog.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ChangedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("changedDate")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime?>("PostDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("postDate")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<byte[]>("Text")
                        .HasColumnType("blob")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("AzerothAPI.Data.Models.Blog.Userpermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.Property<int>("Permission")
                        .HasColumnType("int(100)");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("userpermission", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
